dist: "Xenial" 
language: python
python:
  - "3.9"

addons:
    snaps:
      - name: yq
        channel: v3/stable
      - jq

install:
  - pip3 install -r requirements-dev.txt
  - pip3 install .

script: 
  - pytest

before_deploy:
  - echo TRAVIS_TAG=$TRAVIS_TAG
  - sed -i "s/TRAVISTAGHERE/${TRAVIS_TAG}/g" setup.py
  - cat setup.py

deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: GNXzs+nyElG3AtZ8p70RE9UqiQapUtlGl4qIXLs15BMyUNahknuRN/5XmpkMGsLpTUbY3AzzZP1RB4CbqWaw3YFQg2D7l2jToD14jHQsVM6VNnbGLpuD3YqsM/dqRSzm8nb5smYouvPRDdckh0NvKNX/kw5V8DI05plqWp4kkWg9MRPLTdQph7Y3nTrb20oqvcAO9dkI8Z5jjs2XACdxBgpYDFonxyTqlmDZiLoEo5l1+iwN6jfLICe8cmx9cjMOKzg7AKcmpPnttb7tWksRc5ULDKD+iiT6zCtbG56Hcf6xOM9HMB7mo66TYL3LvHqNs0yBgiTUqN9jShW/JX4GsASuHgoZYQsCC7N19E2GgXpOWMLHvF7JDc+Yhtj2UPNXJpgsKuJB/RWFyalXNv6y6ausdE8xJoIF4KwJpHjSRVne1X1XswCexS9iWINl8Y9YokJVwT9DTHZUT/ke9lJqruALaTfm0OcG25tWkaGB1NiSTiFZHhbcZA0tUp4/X/Ga7oO5xM3Z5HPxWygr77B8SuTRokLt0cKd9Kcmz8HIALrwOXtYdrZRPpWIxa2B1pkWjlj9GbeAhEOSDwp12dLr3hIuZuEUubm4VLVOdz0oa70HUdX3o58GKiWbAC4gXbpPesuyARXKv8QFqw79+Jk6Wm+aT4HhSAD0RljXnfseC1g=
  on:
    tags: true

# ugh, there is some latency in pypi, sleep....
after_deploy:
  - sleep 300
  - found=1; while [ $found -eq 1 ]; do sleep 5; x=$(curl -s https://pypi.org/simple/k8swatcher/ 2>&1 | grep $TRAVIS_TAG); found=$?; echo "found? $found";  done



